"""empty message

Revision ID: 0bd193ce5e6d
Revises: 7e3613066613
Create Date: 2025-04-02 15:48:23.447380

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "0bd193ce5e6d"
down_revision: Union[str, None] = "7e3613066613"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
