"""empty message

Revision ID: 18f9360c4558
Revises: 0420d058ebb8
Create Date: 2025-04-03 21:28:41.458957

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "18f9360c4558"
down_revision: Union[str, None] = "0420d058ebb8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_items",
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("item_id", "order_id"),
    )
    op.drop_table("group_members")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "group_members",
        sa.Column("item_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("order_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"], ["items.id"], name="group_members_item_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name="group_members_order_id_fkey"
        ),
        sa.PrimaryKeyConstraint("item_id", "order_id", name="group_members_pkey"),
    )
    op.drop_table("order_items")
    # ### end Alembic commands ###
