"""empty message

Revision ID: 21bf7d660f1c
Revises: 2ab063755fad
Create Date: 2025-04-02 15:50:29.006018

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "21bf7d660f1c"
down_revision: Union[str, None] = "2ab063755fad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
