"""empty message

Revision ID: 2ab063755fad
Revises: 0bd193ce5e6d
Create Date: 2025-04-02 15:49:43.725296

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "2ab063755fad"
down_revision: Union[str, None] = "0bd193ce5e6d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
